databases:
  - name: slacker-news-db
    databaseName: slacker_news
    user: slacker_news_user
    plan: free
    region: oregon
services:
  - type: cron
    name: slacker-news-hacker-news
    runtime: python
    repo: https://github.com/posthello-code/slacker-news-server
    plan: starter
    envVars:
      - fromGroup: slacker-news
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python -m cron.stories
    schedule: "*/60 * * * *"
  - type: web
    name: slacker-news-server
    previewPlan: free
    previewsExpireAfterDays: 1
    runtime: python
    repo: https://github.com/posthello-code/slacker-news-server
    plan: free
    envVars:
      - fromGroup: slacker-news
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn start:app
    healthCheckPath: /
version: "1"
