databases:
  - name: slacker-news
    databaseName: slacker_news
    user: slacker_news_user
    plan: free
    region: oregon
services:
  - type: cron
    name: slacker-news-hacker-news
    runtime: python
    repo: https://github.com/posthello-code/slacker-news-server
    plan: starter
    envVars:
      - fromGroup: slacker-news
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python -m cron.hackerNews
    schedule: "*/60 * * * *"
version: "1"
